#pragma once

#define I2C1_SCL_PIN GP27
#define I2C1_SDA_PIN GP26


#define LED_PIN_1 GP14
#define LED_PIN_2 GP15

#define WS2812_DI_PIN GP20
#define RGBLIGHT_LED_COUNT 8
#define RGBLIGHT_LIMIT_VAL 5
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_LAYERS
#define RGBLIGHT_CUSTOM_LAYER_EFFECTS

